# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6e018a62f1fded0f3d00a8bc17f640b1613514cf9523ef831639e3879647937527c47c014be5818287028e4a2ac711c567ebb0839cf956b1e9e5b9f3df6e4129

test:
  secret_key_base: 762e57d5faa1bccfa9c1d009092758201cafc32ac4a6e08458f4fcf6540674cca0e6d5b2f24465773fd624442657a601915b65afd702cc173df4dbcfaec9247d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
